trigger:
- main

pool:
  name: Default

variables:
  imageRepository: 'observability-app'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'

steps:
- task: Docker@2
  displayName: Build and push Docker image to Azure Container Registry
  inputs:
    command: buildAndPush
    repository: $(imageRepository)
    dockerfile: $(dockerfilePath)
    containerRegistry: 'acr-observability-service-connection'
    tags: |
      $(tag)
      latest